site_name: Python Портфолио — SplaidEX
site_description: Коллекция моих полезных Python-скриптов
site_author: SplaidEX

theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest

nav:
  - Главная: index.md
  - Проекты: projects.md
  - Обо мне: about.md

extra_css:
  - stylesheets/extra.css